module.exports={
    ON_ACTION_SHEET_INIT:'ON_ACTION_SHEET_INIT',
    ON_ACTION_SHEET_DESTROY:'ON_ACTION_SHEET_DESTROY',
    MAKE_BACK_DROP_VISIBLE:'MAKE_BACK_DROP_VISIBLE',
    MAKE_BACK_DROP_UNVISIBLE:'MAKE_BACK_DROP_UNVISIBLE'
}