module.exports={
    MAKE_NODE_SPREAD:'MAKE_NODE_SPREAD',
    MAKE_NODE_FOLDED:'MAKE_NODE_FOLDED',
    MAKE_NODE_IN_CLASSMETHOD_SPREAD:'MAKE_NODE_IN_CLASSMETHOD_SPREAD',
    MAKE_NODE_IN_CLASSMETHOD_FOLDED:'MAKE_NODE_IN_CLASSMETHOD_FOLDED',
    MAKE_NODE_VISIBLE:'MAKE_NODE_VISIBLE'
}