module.exports={
    ON_GET_NEW_LOGS:'ON_GET_NEW_LOGS',
    ON_GET_NEW_LOG:'ON_GET_NEW_LOG',
    MAKE_CONSOLE_VISIBLE:'MAKE_CONSOLE_VISIBLE',
    MAKE_CONSOLE_UNVISIBLE:'MAKE_CONSOLE_UNVISIBLE',
    CLEAN_ALL_LOGS:'CLEAN_ALL_LOGS'
}