module.exports={
    ON_DATE_PICKER_INIT:'ON_DATE_PICKER_INIT',
    ON_DATE_PICKER_DESTROY:'ON_DATE_PICKER_DESTROY',
    MAKE_BACK_DROP_VISIBLE:'MAKE_BACK_DROP_VISIBLE',
    MAKE_BACK_DROP_UNVISIBLE:'MAKE_BACK_DROP_UNVISIBLE',
    MAKE_DATE_PICKER_MODAL_VISIBLE:'MAKE_DATE_PICKER_MODAL_VISIBLE',
    MAKE_DATE_PICKER_MODAL_INVISIBLE:'MAKE_DATE_PICKER_MODAL_INVISIBLE'
}