
module.exports={
    'DIRECTORY_FOLD':'DIRECTORY_FOLD',
    'DIRECTORY_EXPAND':'DIRECTORY_EXPAND',
    'FETCH_SUB_PATH':'FETCH_SUB_PATH',
    'ON_ROOT_PATH_UPDATE':'ON_ROOT_PATH_UPDATE',
    'ON_FILE_CLICK':'ON_FILE_CLICK',
    'ON_PROJ_PATH_SET':'ON_PROJ_PATH_SET',
    'BACK_TO_PREV':'BACK_TO_PREV',
    CREATE_FILE:'CREATE_FILE',
    SAVE_FILE:'SAVE_FILE',
    WRITE_FILE_DATA:'WRITE_FILE_DATA',
    DELETE_FILE:'DELETE_FILE',
    DELETE_FOLDER:'DELETE_FOLDER'
}
