module.exports={
    ON_MODAL_INIT:'ON_MODAL_INIT',
    ON_MODAL_DESTROY:'ON_MODAL_DESTROY',
    MAKE_BACK_DROP_VISIBLE:'MAKE_BACK_DROP_VISIBLE',
    MAKE_BACK_DROP_UNVISIBLE:'MAKE_BACK_DROP_UNVISIBLE'
}